{"timestamp":"2025-09-07T19:04:25.889865","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-07T19:04:25.891165","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/cdm_c360e_dly_email.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-07T19:04:26.016802","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py:471: DeprecationWarning: Using Connection.get_connection_from_secrets from `airflow.models` is deprecated.Please use `get` on Connection from sdk(`airflow.sdk.Connection`) instead\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-09-07T19:04:26.046584","level":"info","event":"Connection Retrieved 'smtp_default'","logger":"airflow.hooks.base"}
{"timestamp":"2025-09-07T19:04:26.046713","level":"info","event":"Email alerting: attempt 1","logger":"airflow.utils.email"}
{"timestamp":"2025-09-07T19:04:26.048588","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectionRefusedError","exc_value":"[Errno 111] Connection refused","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/cdm_c360e_dly_email.py","lineno":47,"name":"send_custom_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":79,"name":"send_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":154,"name":"send_email_smtp"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":263,"name":"send_mime_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py","lineno":306,"name":"_get_smtp_connection"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":255,"name":"__init__"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":341,"name":"connect"},{"filename":"/usr/local/lib/python3.12/smtplib.py","lineno":312,"name":"_get_socket"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":865,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":850,"name":"create_connection"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-07T19:04:26.104182","level":"error","event":"Top level error","logger":"task","error_detail":[{"exc_type":"UndefinedError","exc_value":"'airflow.sdk.execution_time.task_runner.RuntimeTaskInstance object' has no attribute 'mark_success_url'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1353,"name":"main"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1330,"name":"finalize"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1161,"name":"_send_task_error_email"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py","lineno":411,"name":"_get_email_subject_content"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py","lineno":408,"name":"render"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py","lineno":244,"name":"render_template_to_string"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/helpers.py","lineno":239,"name":"render_template"},{"filename":"<template>","lineno":26,"name":"root"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/jinja2/runtime.py","lineno":859,"name":"_fail_with_undefined_error"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-07T19:04:26.123092Z","level":"warning","event":"Process exited abnormally","exit_code":1,"logger":"task"}
